CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Currencies" (
    "ISONumCodeId" integer GENERATED BY DEFAULT AS IDENTITY,
    "ISOCharCode" text NOT NULL,
    "CurrencyName" text NOT NULL,
    "CurrencyEngName" text NOT NULL,
    CONSTRAINT "PK_Currencies" PRIMARY KEY ("ISONumCodeId")
);

CREATE TABLE "CurrenciesRate" (
    "NumCodeId" integer NOT NULL,
    "CurrencyRateDate" date NOT NULL,
    "Nominal" integer NOT NULL,
    "Value" numeric NOT NULL,
    CONSTRAINT "PK_CurrenciesRate" PRIMARY KEY ("NumCodeId"),
    CONSTRAINT "FK_CurrenciesRate_Currencies_NumCodeId" FOREIGN KEY ("NumCodeId") REFERENCES "Currencies" ("ISONumCodeId") ON DELETE CASCADE
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240803111115_Initial', '8.0.7');

COMMIT;

