// <auto-generated />
using System;
using Corteos.Test.CurrenciesRateWorker.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Corteos.Test.CurrenciesRateWorker.Migrations
{
    [DbContext(typeof(CurrencyDbContext))]
    partial class CurrencyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Corteos.Test.CurrenciesRateWorker.Models.CurrencyEntity", b =>
                {
                    b.Property<int>("ISONumCodeId")
                        .HasColumnType("integer");

                    b.Property<string>("CurrencyEngName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ISOCharCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ISONumCodeId");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Corteos.Test.CurrenciesRateWorker.Models.CurrencyRateEntity", b =>
                {
                    b.Property<int>("NumCodeId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("CurrencyRateDate")
                        .HasColumnType("date");

                    b.Property<int>("Nominal")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("NumCodeId", "CurrencyRateDate");

                    b.ToTable("CurrenciesRate");
                });

            modelBuilder.Entity("Corteos.Test.CurrenciesRateWorker.Models.CurrencyRateEntity", b =>
                {
                    b.HasOne("Corteos.Test.CurrenciesRateWorker.Models.CurrencyEntity", "Currency")
                        .WithMany("CurrenciesRate")
                        .HasForeignKey("NumCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("Corteos.Test.CurrenciesRateWorker.Models.CurrencyEntity", b =>
                {
                    b.Navigation("CurrenciesRate");
                });
#pragma warning restore 612, 618
        }
    }
}
